id: I89707807
ocr_import_info:
  timestamp: '2023-08-22T03:30:49.671093+00:00'
  batch_id: batch-be69
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-22 04:05:28.935940+00:00
last_modified: 2023-08-22 04:05:28.935945+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9041
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9041
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་འཇུག་པའི་འབྲུ་འགྲེལ་བློ་གསལ་དགའ་བའི་མེ་ལོང་སོགས།
  languages:
  - bo
  author: མཁན་པོ་ངག་དགའ
statistics:
  ocr_word_mean_confidence_index: 0.9949269646718569
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG9072:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9072
      total_pages: 334
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9072.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9949269646718569
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
